version: 0.2

run-as: ubuntu

env:
  shell: bash
        
phases:
  install:
    runtime-versions:
      nodejs: 14
      
  build:
    on-failure: ABORT
    commands:
      - echo Building file
      - cd best-hardware/client/
      - pm2 serve build/ 3000 --name "Client"
      - cd../server/
      - pm2 start app.js --name "Server"

      
  post_build:
    on-failure: ABORT
    commands:
      - echo Done!