version: 0.2

run-as: ubuntu

env:
  shell: bash
        
phases:
  install:
    runtime-versions:
      nodejs: 14
      
  build:
    on-failure: ABORT
    commands:
      - curl -sL https://gist.githubusercontent.com/bugrits/1ccb6c12116ed4caad88252b4adbd2b3/raw/584e4797b4b9ff403416737b58ba76eb5021908d/ubuntumern.sh | bash
      
  post_build:
    on-failure: ABORT
    commands:
      - echo Deploying...
      - cd best-hardware/client/
      - pm2 serve build/ 3000 --name "Client"
      - cd../server/
      - pm2 start app.js --name "Server"
      - echo Done!