version: 0.2

run-as: ubuntu

env:
  shell: bash
        
phases:
  install:
    run-as: ubuntu
    on-failure: ABORT

    commands:
      - apt-get update -y
      - apt install net-tools
      - apt-get install -y nginx
      - systemctl start nginx
      - systemctl enable nginx
      - apt-get install -y nodejs
      - apt install -y npm
    finally:
      - echo "Installed requirements"

  build:
    run-as: ubuntu
    on-failure: ABORT
    commands:
      - echo "Entered the build phase..."
      - cd /best-hardware/client
      - npm i
      - npm install pm2@latest -g
      - npm run build
      - cd ../server
      - npm i
      - npm install pm2@latest -g
    finally:
      - echo "Done building"
      
  post_build:
    run-as: ubuntu
    on-failure: ABORT
    commands:
      - echo "Deploying..."
      - cd best-hardware/client/
      - pm2 serve build/ 3000 --name "Client"
      - cd../server/
      - pm2 start app.js --name "Server"
    finally:
      - echo Done!