version: 0.2

run-as: ubuntu

env:
  shell: bash
        
phases:
  install:
    runtime-versions:
      nodejs: 14
      
  build:
    on-failure: CONTINUE

  post_build:
    on-failure: CONTINUE